version: '2'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - data-volume:/data/db
    ports:
      - 27017:27017

  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
  node-app:
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    build: .   
    links: 
      - mongo
    environment:
      - DB_URI=mongodb://root:example@mongo:27017/Ticket_Management?authSource=admin
  
volumes:
  data-volume: